(print "Enter number: ")
(terpri)
(setq x  (read))
(defun factorial(n)
    (if (or (= n 1) (= n 0))
            (setq a 1)
    )
    (if (> n 1)
        (setq a (* n (factorial (- n 1))))
    )
    a 
)
(format t "~d! is " x)

(write ((lambda (x) (factorial x)) x))
